name: capstone
description: "2025CapStone"
publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_maps_flutter: ^2.12.1
  geolocator: ^13.0.4
  http: ^1.3.0
  flutter_local_notifications: ^19.0.0
  intl: ^0.20.2
  table_calendar: ^3.2.0
  shared_preferences: ^2.5.3
  geocoding: ^3.0.0
  workmanager: ^0.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
